services:
  ft_onion:
    build: .
    container_name: ft_onion
    ports:
      - "80"
      - "8022:4242"
    volumes:
      - tor-data:/var/lib/tor
    restart: unless-stopped

volumes:
  tor-data: